### ISSUE TITLE
ruby-dnn

### ISSUE THREAD

**Issue by kojix2** [arbox/machine-learning-with-ruby#26]
Hello.

I vote for ruby-dnn.
ruby-dnn is yet another library of deep learning in Ruby.
https://github.com/unagiootoro/ruby-dnn

Let's look into the examples directory. 
https://github.com/unagiootoro/ruby-dnn/tree/master/examples
You will find that ruby-dnn's API is more Rubyish than any other deep learning library for Ruby. ruby-dnn even has a dcgan example.

The problem with ruby-dnn is the lack of GPU support. The author use Windows and cumo cannot be built. So it will take a very long time to actually run DCGAN example. (To be honest, I haven't tried it.) Ruby-dnn project appears to be a personal project and may not be intended for production.

Despite these shortcomings, ruby-dnn is a valuable project for implementing deep learning in pure Ruby.

If you feel it's too early to list it, please wait until it is mature.

Thank you.

**Comment by arbox** [comment]
@kojix2 

feel free to open a PR :)
